#database
spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://192.168.80.115:13306/snet
      username: sgdbadm
      password: sgdbadm$2015
      #idbc-url: jdbc:log4jdbc:mariadb://localhost:3306/snet
      #username: root
      #password: 1234
  servelt:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      location: ${java.io.tmpdir}
      max-file-size: 2MB
      max-request-size: 2MB

##language
smartguard:
  v3:
    lang: KO
    debug:
      async: true
      diagnosis: true

#Local Test
#ServerIP=150.23.24.39

#SERVER
server:
  port: 10225

##file-location
#sgn.file.default-path=d:/filetest
#sgn.file.default-was-home=d:/filetest


#\uac1c\ubc1c\uc6a9
#temp-directory=c:/test
#audit-directory=c:/test/home/mobigen
#NET_CONF_FILE-directory=c:/test/home/mobigen
#WEB_AUDIT_REG-directory=c:/test/home/sgwas
#audit_asset-directory=c:/test/home/mobigen/service/systemInfo
#LIB_FILE-directory=c:/test/home/sgwas
#excel-directory=c:/test/home/sgwas/excel/
#excel.temp-directory=c:/test/home/excel/temp

